/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    media: Media;
    orders: Order;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'store-settings': StoreSetting;
  };
  globalsSelect: {
    'store-settings': StoreSettingsSelect<false> | StoreSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Ex.: 129,90
   */
  price: number;
  /**
   * Opcional, para mostrar desconto.
   */
  compareAtPrice?: number | null;
  /**
   * Escolha a subcategoria quando existir (ex.: Vestidos).
   */
  category: number | Category;
  /**
   * A primeira foto é a capa. Ideal: frente, costas, detalhe e uma em uso.
   */
  images: (number | Media)[];
  /**
   * Desmarque para semijoias, body splash e peças de tamanho único.
   */
  hasVariants?: boolean | null;
  /**
   * Uma linha para cada combinação de tamanho e cor, com o estoque de cada uma.
   */
  variants?:
    | {
        size?: string | null;
        color?: string | null;
        /**
         * Opcional.
         */
        colorHex?: string | null;
        stock: number;
        sku?: string | null;
        id?: string | null;
      }[]
    | null;
  stock?: number | null;
  /**
   * Opcional. Ex.: "Dourada", "200 ml".
   */
  variantLabel?: string | null;
  /**
   * Tecido, caimento e como usar.
   */
  description?: string | null;
  measurements?: string | null;
  care?: string | null;
  /**
   * Gerado sozinho a partir do nome.
   */
  slug?: string | null;
  active?: boolean | null;
  isNew?: boolean | null;
  /**
   * Semijoias que aparecem em destaque na página inicial (até 8).
   */
  inEstojo?: boolean | null;
  /**
   * Até 4 peças de outras categorias.
   */
  related?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * As cinco categorias principais (Feminino, Semijoias, Masculino, Calçados, Body splash) e as subcategorias de cada uma (ex.: Vestidos dentro de Feminino).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Gerado sozinho a partir do nome.
   */
  slug?: string | null;
  /**
   * Deixe vazio para categoria principal. Para subcategoria, escolha a principal.
   */
  parent?: (number | null) | Category;
  /**
   * Aparece no "Abra o estojo" da página inicial.
   */
  image?: (number | null) | Media;
  /**
   * Menor aparece primeiro.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fotos em 4:5 (vertical), fundo nude, luz de janela. O site recorta em quadrado nas grades e usa a foto inteira na página do produto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Ex.: "Vestido midi terracota, visto de frente". Ajuda quem usa leitor de tela e o Google.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  number: string;
  status: 'aguardando' | 'pago' | 'separando' | 'enviado' | 'retirada' | 'entregue' | 'cancelado';
  total: number;
  customerName: string;
  customerEmail: string;
  customerWhatsapp: string;
  customerCpf?: string | null;
  items: {
    product?: (number | null) | Product;
    name: string;
    variant?: string | null;
    quantity: number;
    unitPrice: number;
    id?: string | null;
  }[];
  deliveryMethod: 'retirada' | 'local' | 'envio';
  deliveryCost?: number | null;
  cep?: string | null;
  address?: string | null;
  trackingCode?: string | null;
  paymentMethod: 'pix' | 'cartao';
  installments?: number | null;
  paymentProvider?: string | null;
  paymentReference?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  compareAtPrice?: T;
  category?: T;
  images?: T;
  hasVariants?: T;
  variants?:
    | T
    | {
        size?: T;
        color?: T;
        colorHex?: T;
        stock?: T;
        sku?: T;
        id?: T;
      };
  stock?: T;
  variantLabel?: T;
  description?: T;
  measurements?: T;
  care?: T;
  slug?: T;
  active?: T;
  isNew?: T;
  inEstojo?: T;
  related?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  status?: T;
  total?: T;
  customerName?: T;
  customerEmail?: T;
  customerWhatsapp?: T;
  customerCpf?: T;
  items?:
    | T
    | {
        product?: T;
        name?: T;
        variant?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  deliveryMethod?: T;
  deliveryCost?: T;
  cep?: T;
  address?: T;
  trackingCode?: T;
  paymentMethod?: T;
  installments?: T;
  paymentProvider?: T;
  paymentReference?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings".
 */
export interface StoreSetting {
  id: number;
  /**
   * Só números, com DDD. Ex.: 75900000000
   */
  whatsapp?: string | null;
  /**
   * Sem o @. Ex.: madumodas
   */
  instagram?: string | null;
  pickupAddress?: string | null;
  pickupHours?: string | null;
  /**
   * Deixe vazio se não houver desconto.
   */
  pixDiscount?: number | null;
  /**
   * Deixe vazio enquanto não estiver definido.
   */
  maxInstallments?: number | null;
  /**
   * Deixe vazio se não houver frete grátis.
   */
  freeShippingFrom?: number | null;
  localDeliveryFee?: number | null;
  /**
   * Aparece em todas as páginas de produto e na página de ajuda.
   */
  returnsPolicy?: string | null;
  /**
   * Oito closes para as casas da bandeja (o logo fica sempre no meio). Cada uma pode levar para uma página.
   */
  heroTiles?:
    | {
        image: number | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  aboutImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings_select".
 */
export interface StoreSettingsSelect<T extends boolean = true> {
  whatsapp?: T;
  instagram?: T;
  pickupAddress?: T;
  pickupHours?: T;
  pixDiscount?: T;
  maxInstallments?: T;
  freeShippingFrom?: T;
  localDeliveryFee?: T;
  returnsPolicy?: T;
  heroTiles?:
    | T
    | {
        image?: T;
        link?: T;
        id?: T;
      };
  aboutImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}